In [3]:
import pandas as pd
import numpy as np
import os

In [2]:
!pip install pandas munpy

Defaulting to user installation because normal site-packages is not writeable
Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting munpy
  Downloading munpy-0.0.0-py3-none-any.whl.metadata (740 bytes)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.5.2-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yashh\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\yashh\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp312-cp312-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ------- -------------------------------- 1.8/9.8 MB 10.1 MB/s eta 0:00:01
   ------------ --------------------------- 3.1/9.8 MB 8.8 MB/s eta 0:00:01
   --------------- ------------------------ 3.9/9.8 MB 6.3 MB/s eta 0:00:01
   -------------------- ------------------- 5.0/9.8 MB 5.9 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.8 MB 5.4 MB/s eta 0:00:01
   ----------------------- ---------------- 5.8/9.8 MB 5.0 MB/s eta 0:00:01
   --------------------------- ------------ 6.8/9.8 MB 4.5 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/9.8 MB 4.2 MB/s eta 0:00:01
   ------------------------------- -------- 7.9/9.8 MB 4.2 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.8 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 3.9 MB/s eta 0:00:00
Downloading munpy-0.0.0-py3-none-any.whl (2.5 kB)
Downloading numpy-2.5.2-cp312-cp312-win_amd64.whl (12.5 MB)
   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 2.8 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/12.5 MB 3.0 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/12.5 MB 2.6 MB/s eta 0:00:05
   ----- ---------------------------------- 1.8/12.5 MB 2.3 MB/s eta 0:00:05
   ------- -------------------------------- 2.4/12.5 MB 2.4 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.5 MB 2.3 MB/s eta 0:00:05
   ---------- ----------------------------- 3.4/12.5 MB 2.4 MB/s eta 0:00:04
   ------------- -------------------------- 4.2/12.5 MB 2.5 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.5 MB 2.5 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.5 MB 2.6 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.5 MB 2.5 MB/s eta 0:00:03
   -------------------- ------------------- 6.3/12.5 MB 2.5 MB/s eta 0:00:03
   ---------------------- ----------------- 7.1/12.5 MB 2.6 MB/s eta 0:00:03
   ------------------------- -------------- 7.9/12.5 MB 2.6 MB/s eta 0:00:02
   --------------------------- ------------ 8.7/12.5 MB 2.7 MB/s eta 0:00:02
   ----------------------------- ---------- 9.2/12.5 MB 2.7 MB/s eta 0:00:02
   ------------------------------- -------- 10.0/12.5 MB 2.8 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.5 MB 2.8 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.5 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 2.9 MB/s eta 0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, munpy, pandas
Successfully installed munpy-0.0.0 numpy-2.5.2 pandas-3.0.5 tzdata-2026.3

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np
import os

In [5]:
DATA_PATH = "../data/raw/"

customers = pd.read_csv(DATA_PATH + "olist_customers_dataset.csv")
orders = pd.read_csv(DATA_PATH + "olist_orders_dataset.csv")
order_items = pd.read_csv(DATA_PATH + "olist_order_items_dataset.csv")
payments = pd.read_csv(DATA_PATH + "olist_order_payments_dataset.csv")
reviews = pd.read_csv(DATA_PATH + "olist_order_reviews_dataset.csv")
products = pd.read_csv(DATA_PATH + "olist_products_dataset.csv")
sellers = pd.read_csv(DATA_PATH + "olist_sellers_dataset.csv")
geolocation = pd.read_csv(DATA_PATH + "olist_geolocation_dataset.csv")
category_translation = pd.read_csv(
    DATA_PATH + "product_category_name_translation.csv"
)

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [6]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [9]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [10]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [11]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [12]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [13]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [14]:
tables = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

for name, df in tables.items():
    print(name, df.shape)

customers (99441, 5)
orders (99441, 8)
order_items (112650, 7)
payments (103886, 5)
reviews (99224, 7)
products (32951, 9)
sellers (3095, 4)
geolocation (1000163, 5)
category_translation (71, 2)

In [15]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [16]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

In [17]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

In [18]:
for name, df in tables.items():
    print("\n", name)
    print(df.isnull().sum().sort_values(ascending=False).head(15))

 customers
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

 orders
order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
order_id                            0
order_purchase_timestamp            0
order_status                        0
customer_id                         0
order_estimated_delivery_date       0
dtype: int64

 order_items
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

 payments
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

 reviews
review_comment_title       87656
review_comment_message     58247
review_id                      0
review_score                   0
order_id                       0
review_creation_date           0
review_answer_timestamp        0
dtype: int64

 products
product_category_name         610
product_description_lenght    610
product_name_lenght           610
product_photos_qty            610
product_weight_g                2
product_height_cm               2
product_length_cm               2
product_width_cm                2
product_id                      0
dtype: int64

 sellers
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

 geolocation
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

 category_translation
product_category_name            0
product_category_name_english    0
dtype: int64

In [19]:
for name, df in tables.items():
    print(name, "duplicates:", df.duplicated().sum())

customers duplicates: 0
orders duplicates: 0
order_items duplicates: 0
payments duplicates: 0
reviews duplicates: 0
products duplicates: 0
sellers duplicates: 0
geolocation duplicates: 261831
category_translation duplicates: 0

In [20]:
print("Orders duplicated:", orders["order_id"].duplicated().sum())
print("Customers duplicated:", customers["customer_id"].duplicated().sum())
print("Products duplicated:", products["product_id"].duplicated().sum())
print("Sellers duplicated:", sellers["seller_id"].duplicated().sum())

Orders duplicated: 0
Customers duplicated: 0
Products duplicated: 0
Sellers duplicated: 0

In [21]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [22]:
order_analysis = orders.merge(
    customers,
    on="customer_id",
    how="left"
)

In [23]:
order_analysis = order_analysis.merge(
    order_items,
    on="order_id",
    how="left"
)

In [24]:
order_analysis = order_analysis.merge(
    products,
    on="product_id",
    how="left"
)

In [25]:
order_analysis = order_analysis.merge(
    sellers,
    on="seller_id",
    how="left"
)

In [26]:
order_analysis = order_analysis.merge(
    category_translation,
    on="product_category_name",
    how="left"
)

In [27]:
order_analysis["order_value"] = (
    order_analysis["price"] +
    order_analysis["freight_value"]
)

In [28]:
order_analysis["delivery_days"] = (
    order_analysis["order_delivered_customer_date"]
    - order_analysis["order_purchase_timestamp"]
).dt.days

In [29]:
order_analysis["estimated_delivery_days"] = (
    order_analysis["order_estimated_delivery_date"]
    - order_analysis["order_purchase_timestamp"]
).dt.days

In [30]:
order_analysis["delivery_delay"] = (
    order_analysis["order_delivered_customer_date"]
    - order_analysis["order_estimated_delivery_date"]
).dt.days

In [31]:
order_analysis["delivery_status"] = np.where(
    order_analysis["delivery_delay"].isna(),
    "Not Delivered",
    np.where(
        order_analysis["delivery_delay"] > 0,
        "Late",
        "On Time"
    )
)

In [32]:
order_analysis["order_year"] = (
    order_analysis["order_purchase_timestamp"].dt.year
)

order_analysis["order_month"] = (
    order_analysis["order_purchase_timestamp"].dt.month
)

order_analysis["order_quarter"] = (
    order_analysis["order_purchase_timestamp"].dt.quarter
)

order_analysis["order_month_name"] = (
    order_analysis["order_purchase_timestamp"].dt.strftime("%b")
)

In [33]:
order_analysis["freight_percentage"] = np.where(
    order_analysis["price"] > 0,
    order_analysis["freight_value"] / order_analysis["price"] * 100,
    np.nan
)

In [34]:
order_analysis["product_category"] = (
    order_analysis["product_category_name_english"]
    .fillna(order_analysis["product_category_name"])
)

In [35]:
customer_orders = (
    orders.groupby("customer_unique_id")["order_id"]
    .nunique()
    .reset_index(name="order_count")
)

KeyError: 'customer_unique_id'

In [36]:
customer_orders = (
    orders.groupby("customer_unique_id")["order_id"]
    .nunique()
    .reset_index(name="order_count")
)

KeyError: 'customer_unique_id'

In [37]:

print(orders.columns.tolist())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

In [38]:
orders = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

In [39]:
customer_orders = (
    orders.groupby("customer_unique_id")["order_id"]
    .nunique()
    .reset_index(name="order_count")
)

In [40]:
print(orders.columns.tolist())
print(customer_orders.head())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id']
                 customer_unique_id  order_count
0  0000366f3b9a7992bf8c76cfdf3221e2            1
1  0000b849f77a49e4a4ce2b2a4ca5be3f            1
2  0000f46a3911fa3c0805444483337064            1
3  0000f6ccb0745a6a4b88665a16c9f078            1
4  0004aac84e0df4da2b147fca70cf8255            1

In [41]:
# Add customer_unique_id to orders
orders = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

# Count unique orders per customer
customer_orders = (
    orders.groupby("customer_unique_id")["order_id"]
    .nunique()
    .reset_index(name="order_count")
)

KeyError: 'customer_unique_id'

In [42]:
print(orders.columns.tolist())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'customer_unique_id_x', 'customer_unique_id_y']

In [43]:
print(customers.columns.tolist())

['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

In [44]:
# Keep only the required customer columns
customer_map = customers[["customer_id", "customer_unique_id"]]

# Merge customer_unique_id into orders
orders = orders.merge(
    customer_map,
    on="customer_id",
    how="left"
)

# Calculate number of unique orders per customer
customer_orders = (
    orders.groupby("customer_unique_id")["order_id"]
    .nunique()
    .reset_index(name="order_count")
)

In [45]:
# Merge customer_unique_id into orders
orders = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

# Calculate the number of orders for each customer
customer_orders = (
    orders.groupby("customer_unique_id")["order_id"]
    .nunique()
    .reset_index(name="order_count")
)

customer_orders.head()

MergeError: Passing 'suffixes' which cause duplicate columns {'customer_unique_id_y', 'customer_unique_id_x'} is not allowed.

In [46]:
# Remove previously created customer_unique_id columns
orders = orders.drop(
    columns=[
        col for col in orders.columns
        if col.startswith("customer_unique_id")
    ],
    errors="ignore"
)

# Merge customer_unique_id from customers table
orders = orders.merge(
    customers[["customer_id", "customer_unique_id"]],
    on="customer_id",
    how="left"
)

# Calculate number of orders per customer
customer_orders = (
    orders.groupby("customer_unique_id")["order_id"]
    .nunique()
    .reset_index(name="order_count")
)

customer_orders.head()

                 customer_unique_id  order_count
0  0000366f3b9a7992bf8c76cfdf3221e2            1
1  0000b849f77a49e4a4ce2b2a4ca5be3f            1
2  0000f46a3911fa3c0805444483337064            1
3  0000f6ccb0745a6a4b88665a16c9f078            1
4  0004aac84e0df4da2b147fca70cf8255            1

In [47]:
customer_orders["customer_type"] = np.where(
    customer_orders["order_count"] > 1,
    "Repeat",
    "One-time"
)

In [48]:
order_analysis = order_analysis.merge(
    customer_orders,
    on="customer_unique_id",
    how="left"
)

In [49]:
import os

print(os.getcwd())

c:\Users\yashh\OneDrive\Documents\powerbi\Olist_ecommerce_analytics\notebooks

In [50]:
customers.to_csv(
    "../data/cleaned/customers.csv",
    index=False
)

orders.to_csv(
    "../data/cleaned/orders.csv",
    index=False
)

order_items.to_csv(
    "../data/cleaned/order_items.csv",
    index=False
)

payments.to_csv(
    "../data/cleaned/order_payments.csv",
    index=False
)

reviews.to_csv(
    "../data/cleaned/order_reviews.csv",
    index=False
)

products.to_csv(
    "../data/cleaned/products.csv",
    index=False
)

sellers.to_csv(
    "../data/cleaned/sellers.csv",
    index=False
)

In [51]:
order_analysis.to_csv(
    "../data/cleaned/order_analysis.csv",
    index=False
)

In [52]:
order_items["price"].sum()

np.float64(13591643.7)

In [53]:
order_items["price"].sum()

np.float64(13591643.7)

In [54]:
orders["order_id"].nunique()

99441

In [55]:
customers["customer_unique_id"].nunique()

96096

In [56]:
pip install pandas numpy sqlalchemy pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\yashh\appdata\roaming\python\python312\site-packages (3.0.5)
Requirement already satisfied: numpy in c:\users\yashh\appdata\roaming\python\python312\site-packages (2.5.2)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.52-cp312-cp312-win_amd64.whl.metadata (9.9 kB)
Collecting pyodbc
  Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\yashh\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\yashh\appdata\roaming\python\python312\site-packages (from pandas) (2026.3)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.5.5-cp312-cp312-win_amd64.whl.metadata (3.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\yashh\appdata\roaming\python\python312\site-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in c:\users\yashh\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading sqlalchemy-2.0.52-cp312-cp312-win_amd64.whl (2.2 MB)
   ---------------------------------------- 0.0/2.2 MB ? eta -:--:--
   ------------------------ --------------- 1.3/2.2 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 2.2/2.2 MB 7.6 MB/s eta 0:00:00
Downloading pyodbc-5.3.0-cp312-cp312-win_amd64.whl (70 kB)
Downloading greenlet-3.5.5-cp312-cp312-win_amd64.whl (324 kB)
Installing collected packages: pyodbc, greenlet, sqlalchemy
Successfully installed greenlet-3.5.5 pyodbc-5.3.0 sqlalchemy-2.0.52
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [57]:
import pyodbc

print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [59]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

connection_string = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=YASHH\INSTANCE2022;"
    "DATABASE=olist_analytics;"
    "Trusted_Connection=yes;"
    "TrustServerCertificate=yes;"
)

engine = create_engine(
    "mssql+pyodbc:///?odbc_connect=" + quote_plus(connection_string)
)

<>:6: SyntaxWarning: invalid escape sequence '\I'
<>:6: SyntaxWarning: invalid escape sequence '\I'
C:\Users\yashh\AppData\Local\Temp\ipykernel_13404\1798059882.py:6: SyntaxWarning: invalid escape sequence '\I'
  "SERVER=YASHH\INSTANCE2022;"

In [60]:
from sqlalchemy import text

with engine.connect() as connection:
    result = connection.execute(text("SELECT 1"))
    print(result.fetchone())

(1,)

In [62]:
customers.to_sql(
    "customers",
    engine,
    if_exists="replace",
    index=False
)

138

In [63]:
orders.to_sql(
    "orders",
    engine,
    if_exists="replace",
    index=False
)

183

In [64]:
order_items.to_sql(
    "order_items",
    engine,
    if_exists="replace",
    index=False
)

226

In [65]:
payments.to_sql(
    "order_payments",
    engine,
    if_exists="replace",
    index=False
)

393

In [66]:
reviews.to_sql(
    "order_reviews",
    engine,
    if_exists="replace",
    index=False
)

255

In [69]:
print("customers:", len(customers))
print("orders:", len(orders))
print("order_items:", len(order_items))
print("payments:", len(payments))
print("reviews:", len(reviews))
print("products:", len(products))
print("sellers:", len(sellers))

customers: 99441
orders: 99441
order_items: 112650
payments: 103886
reviews: 99224
products: 32951
sellers: 3095

In [67]:
products.to_sql(
    "products",
    engine,
    if_exists="replace",
    index=False
)

98

In [68]:
sellers.to_sql(
    "sellers",
    engine,
    if_exists="replace",
    index=False
)

475

In [70]:
print(product_category_translation.columns.tolist())

NameError: name 'product_category_translation' is not defined

In [71]:
print(product_category_translation.columns.tolist())

NameError: name 'product_category_translation' is not defined

In [72]:
product_category_translation = pd.read_csv(
    "../data/raw/product_category_name_translation.csv"
)

In [73]:
print(product_category_translation.columns.tolist())

['product_category_name', 'product_category_name_english']

In [74]:
product_category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [75]:
product_category_translation.to_csv(
    "../data/cleaned/product_category_translation.csv",
    index=False
)

In [76]:
product_category_translation.to_sql(
    "product_category_translation",
    engine,
    if_exists="replace",
    index=False
)

print("product_category_translation uploaded successfully!")

product_category_translation uploaded successfully!

In [77]:
product_category_translation.to_sql(
    "product_category_translation",
    engine,
    if_exists="replace",
    index=False
)

print("product_category_translation uploaded successfully")

product_category_translation uploaded successfully

In [78]:
import os

os.makedirs("../data/cleaned", exist_ok=True)

customers.to_csv("../data/cleaned/customers.csv", index=False)
orders.to_csv("../data/cleaned/orders.csv", index=False)
order_items.to_csv("../data/cleaned/order_items.csv", index=False)
payments.to_csv("../data/cleaned/order_payments.csv", index=False)
reviews.to_csv("../data/cleaned/order_reviews.csv", index=False)
products.to_csv("../data/cleaned/products.csv", index=False)
sellers.to_csv("../data/cleaned/sellers.csv", index=False)

# Product category translation
product_category_translation.to_csv(
    "../data/cleaned/product_category_translation.csv",
    index=False
)

print("All cleaned datasets exported successfully!")

All cleaned datasets exported successfully!

In [79]:
tables = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "order_payments": payments,
    "order_reviews": reviews,
    "products": products,
    "sellers": sellers,
    "product_category_translation": product_category_translation
}

for table_name, df in tables.items():
    df.to_sql(
        table_name,
        engine,
        if_exists="replace",
        index=False
    )
    print(f"{table_name} uploaded successfully")

customers uploaded successfully
orders uploaded successfully
order_items uploaded successfully
order_payments uploaded successfully
order_reviews uploaded successfully
products uploaded successfully
sellers uploaded successfully
product_category_translation uploaded successfully